# The Guestbook app is configured to use skaffold modules.
# The frontend and backend services can be activated by name,
# allowing each service to be iterated on independently.
# To learn more about skaffold modules and multi-config support,
# visit https://skaffold.dev/docs/design/config/

apiVersion: skaffold/v2beta18
kind: Config
build:
  googleCloudBuild:
    projectId: galloro-demos
  artifacts:
  - image: python-guestbook-backend
    context: ./src/backend
  - image: python-guestbook-frontend
    context: ./src/frontend
deploy:
  kubectl:
    manifests:
    - ./src/backend/kubernetes-manifests/*.yaml
    - ./src/frontend/kubernetes-manifests/*.yaml
portForward:
  # Cloud Code automatically port forwards resources,
  # or users can define explicit port forwards here.
  # For more info, visit https://skaffold.dev/docs/pipeline-stages/port-forwarding/#UDPF
  - resourceType: service
    resourceName: python-guestbook-frontend
    port: 80
    localPort: 4503
